document.addEventListener("DOMContentLoaded", () => {
    const heading = document.createElement("header");
    heading.className = "heading";
    heading.style.display = "flex";
    heading.style.justifyContent = "space-between";
    heading.style.alignItems = "center";
    heading.style.fontSize = "23px";
    heading.style.height = "60px";
    heading.style.backgroundColor = "white";
    heading.style.paddingRight = "20px";
    heading.style.paddingLeft = "20px";
    heading.style.position = "sticky";
    heading.style.top = "0px";

    const headingLeft = document.createElement("div");
    headingLeft.className = "headingDiv";
    headingLeft.innerHTML = "☰";
    const headingMiddle = document.createElement("div");
    headingMiddle.className = "headingDiv";
    headingMiddle.innerHTML = "My Food";
    const headingRight = document.createElement("div");
    headingRight.className = "headingDiv";
    headingRight.innerHTML = "Mail";
    heading.appendChild(headingLeft);
    heading.appendChild(headingMiddle);
    heading.appendChild(headingRight);

    const section = document.createElement("div");
    section.id = "food";

    const bodyTop = document.createElement("div");
    bodyTop.className = "foodRow";
    bodyTop.style.display = "flex";
    bodyTop.style.justifyContent = "center";
    bodyTop.style.gap = "10px";

    const bodyTop1 = document.createElement("div");
    bodyTop1.className = "foodRowItem";
    bodyTop1.style.width = "320px";
    const bodyTop1Img = document.createElement("img");
    bodyTop1Img.id = "bodyTop1Img";
    bodyTop1Img.style.width = "100%";
    bodyTop1Img.style.height = "400px";
    bodyTop1Img.src = "https://www.w3schools.com/w3images/sandwich.jpg";
    const bodyTop1Description = document.createElement("div");
    bodyTop1Description.className = "foodRowItemDescription";
    bodyTop1Description.style.padding = "20px";
    const bodyTop1DescriptionHeading = document.createElement("h3");
    bodyTop1DescriptionHeading.className = "foodRowItemDescriptionHeading";
    bodyTop1DescriptionHeading.innerHTML = "The Perfect Sandwich, A Real NYC Classic";
    const bodyTop1DescriptionText = document.createElement("p");
    bodyTop1DescriptionText.className = "foodRowItemDescriptionText";
    bodyTop1DescriptionText.innerHTML = "Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.";
    bodyTop1.appendChild(bodyTop1Img);
    bodyTop1.appendChild(bodyTop1Description);
    bodyTop1Description.appendChild(bodyTop1DescriptionHeading);
    bodyTop1Description.appendChild(bodyTop1DescriptionText);

    const bodyTop2 = document.createElement("div");
    bodyTop2.className = "foodRowItem";
    bodyTop2.style.width = "320px";
    const bodyTop2Img = document.createElement("img");
    bodyTop2Img.id = "bodyTop2Img";
    bodyTop2Img.style.width = "100%";
    bodyTop2Img.style.height = "400px";
    bodyTop2Img.src = "https://www.w3schools.com/w3images/steak.jpg";
    const bodyTop2Description = document.createElement("div");
    bodyTop2Description.className = "foodRowItemDescription";
    bodyTop2Description.style.padding = "20px";
    const bodyTop2DescriptionHeading = document.createElement("h3");
    bodyTop2DescriptionHeading.className = "foodRowItemDescriptionHeading";
    bodyTop2DescriptionHeading.innerHTML = "Let me Tell you About This Steak";
    const bodyTop2DescriptionText = document.createElement("p");
    bodyTop2DescriptionText.className = "foodRowItemDescriptionText";
    bodyTop2DescriptionText.innerHTML = "Once again, some random text to lorem lorem lorem lorem ipsum textpraesent tincidunt ipsum lipsum.";
    bodyTop2.appendChild(bodyTop2Img);
    bodyTop2.appendChild(bodyTop2Description);
    bodyTop2Description.appendChild(bodyTop2DescriptionHeading);
    bodyTop2Description.appendChild(bodyTop2DescriptionText);
    
    const bodyTop3 = document.createElement("div");
    bodyTop3.className = "foodRowItem";
    bodyTop3.style.width = "320px";
    const bodyTop3Img = document.createElement("img");
    bodyTop3Img.id = "bodyTop3Img";
    bodyTop3Img.style.width = "100%";
    bodyTop3Img.style.height = "400px";
    bodyTop3Img.src = "https://www.w3schools.com/w3images/cherries.jpg";
    const bodyTop3Description = document.createElement("div");
    bodyTop3Description.className = "foodRowItemDescription";
    bodyTop3Description.style.padding = "20px";
    const bodyTop3DescriptionHeading = document.createElement("h3");
    bodyTop3DescriptionHeading.className = "foodRowItemDescriptionHeading";
    bodyTop3DescriptionHeading.innerHTML = "Cherries, interrupted";
    const bodyTop3DescriptionText = document.createElement("p");
    bodyTop3DescriptionText.className = "foodRowItemDescriptionText";
    bodyTop3DescriptionText.innerHTML = "Lorem ipsum text praesent tincidunt ipsum lipsum.";
    bodyTop3.appendChild(bodyTop3Img);
    bodyTop3.appendChild(bodyTop3Description);
    bodyTop3Description.appendChild(bodyTop3DescriptionHeading);
    bodyTop3Description.appendChild(bodyTop3DescriptionText);

    const bodyTop4 = document.createElement("div");
    bodyTop4.className = "foodRowItem";
    bodyTop4.style.width = "320px";
    const bodyTop4Img = document.createElement("img");
    bodyTop4Img.id = "bodyTop4Img";
    bodyTop4Img.style.width = "100%";
    bodyTop4Img.style.height = "400px";
    bodyTop4Img.src = "https://www.w3schools.com/w3images/wine.jpg";
    const bodyTop4Description = document.createElement("div");
    bodyTop4Description.className = "foodRowItemDescription";
    bodyTop4Description.style.padding = "20px";
    const bodyTop4DescriptionHeading = document.createElement("h3");
    bodyTop4DescriptionHeading.className = "foodRowItemDescriptionHeading";
    bodyTop4DescriptionHeading.innerHTML = "Once Again, Robust Wine and Vegetable Pasta";
    const bodyTop4DescriptionText = document.createElement("p");
    bodyTop4DescriptionText.className = "foodRowItemDescriptionText";
    bodyTop4DescriptionText.innerHTML = "Lorem ipsum text praesent tincidunt ipsum lipsum.";
    bodyTop4.appendChild(bodyTop4Img);
    bodyTop4.appendChild(bodyTop4Description);
    bodyTop4Description.appendChild(bodyTop4DescriptionHeading);
    bodyTop4Description.appendChild(bodyTop4DescriptionText);

    bodyTop.appendChild(bodyTop1);
    bodyTop.appendChild(bodyTop2);
    bodyTop.appendChild(bodyTop3);
    bodyTop.appendChild(bodyTop4);

    const bodyBottom = document.createElement("div");
    bodyBottom.className = "foodRow";
    bodyBottom.style.display = "flex";
    bodyBottom.style.justifyContent = "center";
    bodyBottom.style.gap = "10px";

    const bodyBottom1 = document.createElement("div");
    bodyBottom1.className = "foodRowItem";
    bodyBottom1.style.width = "320px";
    const bodyBottom1Img = document.createElement("img");
    bodyBottom1Img.id = "bodyBottom1Img";
    bodyBottom1Img.style.width = "100%";
    bodyBottom1Img.style.height = "400px";
    bodyBottom1Img.src = "https://www.w3schools.com/w3images/popsicle.jpg";
    const bodyBottom1Description = document.createElement("div");
    bodyBottom1Description.className = "foodRowItemDescription";
    bodyBottom1Description.style.padding = "20px";
    const bodyBottom1DescriptionHeading = document.createElement("h3");
    bodyBottom1DescriptionHeading.className ="foodRowItemDescriptionHeading";
    bodyBottom1DescriptionHeading.innerHTML = "All I Need Is a Popsicle";
    const bodyBottom1DescriptionText = document.createElement("p");
    bodyBottom1DescriptionText.className = "foodRowItemDescriptionText";
    bodyBottom1DescriptionText.innerHTML = "Lorem ipsum text praesent tincidunt ipsum lipsum.";
    bodyBottom1.appendChild(bodyBottom1Img);
    bodyBottom1.appendChild(bodyBottom1Description);
    bodyBottom1Description.appendChild(bodyBottom1DescriptionHeading);
    bodyBottom1Description.appendChild(bodyBottom1DescriptionText);

    const bodyBottom2 = document.createElement("div");
    bodyBottom2.className = "foodRowItem";
    bodyBottom2.style.width = "320px";
    const bodyBottom2Img = document.createElement("img");
    bodyBottom2Img.id = "bodyBottom2Img";
    bodyBottom2Img.style.width = "100%";
    bodyBottom2Img.style.height = "400px";
    bodyBottom2Img.src = "https://www.w3schools.com/w3images/salmon.jpg";
    const bodyBottom2Description = document.createElement("div");
    bodyBottom2Description.className = "foodRowItemDescription";
    bodyBottom2Description.style.padding = "20px";
    const bodyBottom2DescriptionHeading = document.createElement("h3");
    bodyBottom2DescriptionHeading.className = "foodRowItemDescriptionHeading";
    bodyBottom2DescriptionHeading.innerHTML = "Salmon For Your Skin";
    const bodyBottom2DescriptionText = document.createElement("p");
    bodyBottom2DescriptionText.className = "foodRowItemDescriptionText";
    bodyBottom2DescriptionText.innerHTML = "Once again, some random text to lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.";
    bodyBottom2.appendChild(bodyBottom2Img);
    bodyBottom2.appendChild(bodyBottom2Description);
    bodyBottom2Description.appendChild(bodyBottom2DescriptionHeading);
    bodyBottom2Description.appendChild(bodyBottom2DescriptionText);

    const bodyBottom3 = document.createElement("div");
    bodyBottom3.className = "foodRowItem";
    bodyBottom3.style.width = "320px";
    const bodyBottom3Img = document.createElement("img");
    bodyBottom3Img.id = "bodyBottom3Img";
    bodyBottom3Img.style.width = "100%";
    bodyBottom3Img.style.height = "400px";
    bodyBottom3Img.src = "https://www.w3schools.com/w3images/sandwich.jpg";
    const bodyBottom3Description = document.createElement("div");
    bodyBottom3Description.className = "foodRowItemDescription";
    bodyBottom3Description.style.padding = "20px";
    const bodyBottom3DescriptionHeading = document.createElement("h3");
    bodyBottom3DescriptionHeading.className = "foodRowItemDescriptionHeading";
    bodyBottom3DescriptionHeading.innerHTML = "The Perfect Sandwich, A real Classic";
    const bodyBottom3DescriptionText = document.createElement("p");
    bodyBottom3DescriptionText.className = "foodRowItemDescriptionText";
    bodyBottom3DescriptionText.innerHTML = "Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.";
    bodyBottom3.appendChild(bodyBottom3Img);
    bodyBottom3.appendChild(bodyBottom3Description);
    bodyBottom3Description.appendChild(bodyBottom3DescriptionHeading);
    bodyBottom3Description.appendChild(bodyBottom3DescriptionText);

    const bodyBottom4 = document.createElement("div");
    bodyBottom4.className = "foodRowItem";
    bodyBottom4.style.width = "320px";
    const bodyBottom4Img = document.createElement("img");
    bodyBottom4Img.id = "bodyBottom4Img";
    bodyBottom4Img.style.width = "100%";
    bodyBottom4Img.style.height = "400px";
    bodyBottom4Img.src = "https://www.w3schools.com/w3images/croissant.jpg";
    const bodyBottom4Description = document.createElement("div");
    bodyBottom4Description.className = "foodRowItemDescription";
    bodyBottom4Description.style.padding = "20px";
    const bodyBottom4DescriptionHeading = document.createElement("h3");
    bodyBottom4DescriptionHeading.className = "foodRowItemDescriptionHeading";
    bodyBottom4DescriptionHeading.innerHTML = "Le French";
    const bodyBottom4DescriptionText = document.createElement("p");
    bodyBottom4DescriptionText.className = "foodRowItemDescriptionText";
    bodyBottom4DescriptionText.innerHTML = "Lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.";
    bodyBottom4.appendChild(bodyBottom4Img);
    bodyBottom4.appendChild(bodyBottom4Description);
    bodyBottom4Description.appendChild(bodyBottom4DescriptionHeading);
    bodyBottom4Description.appendChild(bodyBottom4DescriptionText);

    bodyBottom.appendChild(bodyBottom1);
    bodyBottom.appendChild(bodyBottom2);
    bodyBottom.appendChild(bodyBottom3);
    bodyBottom.appendChild(bodyBottom4);

    section.appendChild(bodyTop);
    section.appendChild(bodyBottom);

    const body = document.getElementsByTagName("body")[0];
    body.style.fontFamily = "Cambria, Cochin, Georgia, Times, Times New Roman, serif"
    body.style.margin = "0 auto"
    body.style.maxWidth = "1280px"
    body.appendChild(heading);
    body.appendChild(section);
});